Merge pull request #1 from MkSavin/master
MkSavin/Schedule pull request #3
Opened 2020-09-14 08:12 UTC by Kuppuch

Fork synchronization

2020-09-14 08:13 UTC, Kuppuch commented
Nothing comment

2020-09-16 08:11 UTC, MkSavin requested changes

2020-09-16 08:11 UTC, MkSavin commented on seventh/index.html
> +							<div class="group-location">А/Б <span>418-2</span></div>
В расписании у нас 410-2

2020-09-16 08:11 UTC, MkSavin commented on seventh/index.html
> +							<div class="group-location">А/Б <span>418-2</span></div>
Аналогично предыдущему комментарию, 410-2

2020-09-16 13:11 UTC, MkSavin approved these changes

2020-09-16 13:17 UTC, merged